package com;
// Generated 17 Aug, 2022 3:16:46 PM by Hibernate Tools 4.3.1



/**
 * Productdetails generated by hbm2java
 */
public class Productdetails  implements java.io.Serializable {


     private int pid;
     private String pname;
     private int pprice;
     private int pquantity;

    public Productdetails() {
    }

	
    public Productdetails(int pid) {
        this.pid = pid;
    }
    public Productdetails(int pid, String pname, int pprice, int quantity) {
       this.pid = pid;
       this.pname = pname;
       this.pprice = pprice;
       this.pquantity = quantity;
    }
   
    public int getPid() {
        return this.pid;
    }
    
    public void setPid(int pid) {
        this.pid = pid;
    }
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }
    public int getPprice() {
        return this.pprice;
    }
    
    public void setPprice(int pprice) {
        this.pprice = pprice;
    }
    public Integer getQuantity() {
        return this.pquantity;
    }
    
    public void setQuantity(int quantity) {
        this.pquantity = quantity;
    }




}


